import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#D9DEE3',
  },
  aquaticBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  waterGlowLarge: {
    position: 'absolute',
    top: -70,
    right: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
  },
  waterGlowSmall: {
    position: 'absolute',
    top: 180,
    left: -50,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(128, 208, 247, 0.24)',
  },
  headerWaveBack: {
    position: 'absolute',
    top: 86,
    left: -40,
    right: -40,
    height: 86,
    borderRadius: 90,
    backgroundColor: '#9CCEF1',
    opacity: 0.6,
  },
  headerWaveFront: {
    position: 'absolute',
    top: 102,
    left: -25,
    right: -25,
    height: 78,
    borderRadius: 90,
    backgroundColor: '#BEE0F7',
  },
  header: {
    marginTop: 12,
    paddingHorizontal: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIcon: {
    fontSize: 28,
    color: '#1D2935',
  },
  headerCenter: {
    alignItems: 'center',
  },
  headerTitle: {
    color: '#1F8FD7',
    fontSize: 36,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  headerSubtitle: {
    marginTop: 2,
    color: '#7D95AA',
    fontSize: 12,
    writingDirection: 'rtl',
  },
  scrollContent: {
    paddingHorizontal: 12,
    paddingTop: 24,
    paddingBottom: 24,
  },
  mainCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#8CC6ED',
    backgroundColor: '#F3F5F8',
    padding: 16,
    paddingBottom: 20,
  },
  sectionTitle: {
    color: '#2B6D9F',
    fontSize: 31,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  instructorRow: {
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: '#E7E9EE',
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  instructorMetaWrap: {
    alignItems: 'flex-end',
    flexShrink: 1,
  },
  instructorName: {
    color: '#2C75AE',
    fontSize: 31,
    writingDirection: 'rtl',
  },
  instructorExpertise: {
    color: '#9AA3AB',
    fontSize: 16,
    marginTop: 1,
    writingDirection: 'rtl',
  },
  editButton: {
    marginTop: 6,
    backgroundColor: '#2994DD',
    borderRadius: 16,
    minWidth: 74,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  avatarCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#2DABE8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  addButtonShell: {
    marginTop: 16,
    borderRadius: 22,
    overflow: 'hidden',
    alignSelf: 'center',
    width: '84%',
    maxWidth: 340,
  },
  addButton: {
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  createSectionTitle: {
    marginTop: 18,
    fontSize: 24,
  },
  accountTypeRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  accountTypeChip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#8EC4E8',
    backgroundColor: '#EAF4FB',
    minWidth: 86,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  accountTypeChipActive: {
    backgroundColor: '#2F8FCE',
    borderColor: '#2F8FCE',
  },
  accountTypeChipText: {
    color: '#2F8FCE',
    fontSize: 15,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  accountTypeChipTextActive: {
    color: '#FFFFFF',
  },
  sessionWarning: {
    marginTop: 12,
    color: '#C95A4A',
    fontSize: 13,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  fieldLabel: {
    marginTop: 10,
    color: '#6A8399',
    fontSize: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  input: {
    marginTop: 6,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#BCD6E9',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    color: '#213344',
  },
});

export default styles;
