import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#E9F2FA',
  },
  headerWaveBack: {
    position: 'absolute',
    top: 78,
    left: -40,
    right: -40,
    height: 88,
    borderRadius: 96,
    backgroundColor: '#9CCEF1',
    opacity: 0.6,
  },
  headerWaveFront: {
    position: 'absolute',
    top: 98,
    left: -26,
    right: -26,
    height: 80,
    borderRadius: 96,
    backgroundColor: '#BEE0F7',
  },
  header: {
    marginTop: 14,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  headerIcon: {
    fontSize: 26,
    color: '#1D2935',
  },
  headerCenter: {
    alignItems: 'center',
  },
  headerTitle: {
    color: '#1F8FD7',
    fontSize: 30,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  headerSubtitle: {
    marginTop: 2,
    color: '#7D95AA',
    fontSize: 12,
    writingDirection: 'rtl',
  },
  headerDate: {
    marginTop: 8,
    textAlign: 'center',
    color: '#36568A',
    fontSize: 16,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  chipRow: {
    marginTop: 16,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  chip: {
    flex: 1,
    marginHorizontal: 4,
    borderRadius: 16,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#A5C8E4',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#355E8E',
    writingDirection: 'rtl',
  },
  mainCard: {
    marginTop: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#8CC6ED',
    backgroundColor: '#F7FAFE',
    padding: 14,
    paddingBottom: 18,
  },
  sectionTitle: {
    color: '#2B6D9F',
    fontSize: 24,
    textAlign: 'right',
    writingDirection: 'rtl',
  },
  groupRow: {
    marginTop: 12,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    elevation: 2,
  },
  cancelButton: {
    backgroundColor: '#ED4753',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    minWidth: 84,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 14,
    writingDirection: 'rtl',
  },
  groupTextWrap: {
    alignItems: 'flex-end',
    flex: 1,
    marginRight: 8,
  },
  groupTitle: {
    color: '#2C75AE',
    fontSize: 20,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
  groupSubtitle: {
    color: '#A2A7AE',
    fontSize: 14,
    marginTop: 3,
    writingDirection: 'rtl',
  },
  bottomActions: {
    marginTop: 16,
    gap: 10,
  },
  actionButton: {
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 4,
  },
  actionButtonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
    writingDirection: 'rtl',
  },
});

export default styles;
